name: "raccoontools-db: vet OSS Components"

on:
  pull_request:
    paths:
      - 'raccoontools-db/**'
  push:
    branches:
      - master
    paths:
      - 'raccoontools-db/**'

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run vet
        id: vet
        uses: safedep/vet-action@5647f2e7f0a1b2fa735f0d7fcd73255bc2512a3a # v1.1.9
        with:
          policy: .github/vet/policy.yml
          path: raccoontools-db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@7fd177fa680c9881b53cdab4d346d32574c9f7f4 # v3.35.4
        if: ${{ steps.vet.outputs.report != '' }}
        with:
          sarif_file: ${{ steps.vet.outputs.report }}
          category: vet-raccoontools-db
